In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt
import seaborn as sns
data=pd.read_csv("C:\\Users\\dazvi\\Downloads\\List of languages by total number of speakers.csv")
data.head()
#as we can see there is a unamed column

,Unnamed: 0,Language,Family,Branch,First-language(L1) speakers,Second-language(L2) speakers,Total speakers(L1+L2)
0,0,English(excl. creole languages),Indo-European,Germanic,372.9 million,1.080 billion[5],1.452 billion
1,1,"Mandarin Chinese(incl. Standard Chinese, but e...",Sino-Tibetan,Sinitic,929.0 million,198.7 million[6],1.118 billion
2,2,Hindi(excl. Urdu),Indo-European,Indo-Aryan,343.9 million,258.3 million[7],602.2 million
3,3,Spanish,Indo-European,Romance,474.7 million,73.6 million[8],548.3 million
4,4,French,Indo-European,Romance,79.9 million,194.2 million[9],274.1 million

In [2]:
data.drop('Unnamed: 0', axis=1, inplace=True)
data.head()

,Language,Family,Branch,First-language(L1) speakers,Second-language(L2) speakers,Total speakers(L1+L2)
0,English(excl. creole languages),Indo-European,Germanic,372.9 million,1.080 billion[5],1.452 billion
1,"Mandarin Chinese(incl. Standard Chinese, but e...",Sino-Tibetan,Sinitic,929.0 million,198.7 million[6],1.118 billion
2,Hindi(excl. Urdu),Indo-European,Indo-Aryan,343.9 million,258.3 million[7],602.2 million
3,Spanish,Indo-European,Romance,474.7 million,73.6 million[8],548.3 million
4,French,Indo-European,Romance,79.9 million,194.2 million[9],274.1 million

In [3]:
# Lets view shape of the data
data.shape

(45, 6)

In [ ]:
# Lets find if there is any duplicate value in the dataset
data.duplicated().any()